name: redux_generator
description: Using Dart's package:build to generate Redux classes.
version: 0.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  redux: ^5.0.0
  build: ^2.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_config: ^1.0.0
  build_runner: ^2.0.6
